import Link from "next/link";
import { evidenceNoteStatus, coherentReferencedEvidenceIds, type CoherentBuilderResult } from "@/lib/topic-builder-core";

export function CoherentTopicReview({result,documents}:{result:CoherentBuilderResult;documents:Array<{id:string;title:string}>}){
  const cited=coherentReferencedEvidenceIds(result),tags=new Map(cited.map((id,index)=>[id,`S${index+1}`]));
  const evidenceById=new Map(result.evidence.map(item=>[item.id,item]));
  const claim=(item:{text:string;evidenceId:string})=>{const source=evidenceById.get(item.evidenceId);return <p key={`${item.evidenceId}-${item.text}`} className="leading-6">{item.text} <a className="font-medium underline" href={`#source-${item.evidenceId}`}>[{tags.get(item.evidenceId)}]</a>{source&&<span className="ml-2 text-xs text-muted-foreground">{source.documentTitle}, p. {source.page}</span>}</p>;};
  const subsection=(title:string,items:Array<{text:string;evidenceId:string}>)=>items.length>0&&<section className="space-y-2"><h4 className="font-medium">{title}</h4>{items.map(claim)}</section>;
  return <article className="my-4 space-y-5 rounded-md bg-muted/40 p-4">
    <div><h3 className="text-lg font-semibold">{result.title}</h3><p className="mt-1 text-xs text-muted-foreground">One coherent topic · {result.formatVersion} · evidence notes describe retrieved support, not completeness</p></div>
    <section className="space-y-2"><h4 className="font-medium">Scope</h4>{result.sections.scope.map(claim)}</section>
    <section className="space-y-3"><h4 className="font-medium">System overview</h4>{subsection("Function",result.sections.overview.function)}{subsection("Location",result.sections.overview.location)}{subsection("Components and interfaces",result.sections.overview.components)}{subsection("Operation and indications",result.sections.overview.operation)}{subsection("Procedure purpose and scope — review carefully",result.sections.overview.procedurePurpose)}{result.sections.overview.procedurePurpose.length>0&&<p className="text-xs text-amber-700">This note must describe purpose and scope only. It must not contain operational actions or steps; human review is required before approval.</p>}</section>
    <section className="space-y-2"><h4 className="font-medium">Limits and specifications</h4>{result.sections.limits.length?<div className="overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead><tr>{["Item","Source value","Context","Source"].map(label=><th key={label} className="border p-2">{label}</th>)}</tr></thead><tbody>{result.sections.limits.map((row,index)=><tr key={`${row.evidenceId}-${index}`}><td className="border p-2">{row.name}</td><td className="border p-2 font-mono">{row.value}</td><td className="border p-2">{row.context}</td><td className="border p-2"><a className="underline" href={`#source-${row.evidenceId}`}>[{tags.get(row.evidenceId)}]</a></td></tr>)}</tbody></table></div>:<p className="text-sm text-muted-foreground">No supported limits or specifications were retrieved.</p>}</section>
    <section className="space-y-3"><h4 className="font-medium">Differences and open questions</h4>{result.sections.differences.length?result.sections.differences.map(difference=><div key={difference.id} className="rounded border p-3"><h5 className="font-medium">Potential difference: {difference.id.replaceAll("-"," ")} <span className="text-xs text-muted-foreground">({result.review?.differenceReasons[difference.id]??difference.reason})</span></h5><div className="mt-2 space-y-2">{difference.positions.map(claim)}</div></div>):<p className="text-sm text-muted-foreground">No material differences were identified in retrieved evidence; this is not a completeness claim.</p>}</section>
    <section className="space-y-2"><h4 className="font-medium">Evidence notes</h4><p className="text-xs text-muted-foreground">These labels describe how much validated evidence was retrieved for each question; they do not mean the topic is complete.</p><ul className="grid gap-2 md:grid-cols-2">{result.evidenceNotes.map(note=><li key={note.lens} className="rounded border p-2 text-sm"><span className="font-medium">{note.lens.replaceAll("_"," ")}</span><span className="ml-2 rounded bg-background px-2 py-0.5 text-xs">{evidenceNoteStatus(note)}</span>{note.gap&&<p className="mt-1 text-xs text-muted-foreground">{note.gap}</p>}</li>)}</ul></section>
    {(result.applicabilityAudit.unknown.length>0||result.applicabilityAudit.excluded.length>0||result.applicabilityAudit.resolution==="unresolved")&&<section className="rounded border border-amber-500 p-3"><h4 className="font-medium">Applicability review</h4><p className="text-xs text-muted-foreground">Requested: {result.applicabilityAudit.requested} · matched families: {result.applicabilityAudit.requestedFamilies.join(", ")||"not resolved"}</p><p className="mt-1 text-xs text-muted-foreground">Source-page applicability resolved: {result.applicabilityAudit.sourcePagesResolved}/{result.applicabilityAudit.sourcePagesTotal} ({result.applicabilityAudit.sourcePageResolutionPercent}%). This is a metadata check, not a claim that all pages were retrieved.</p>{result.applicabilityAudit.resolution==="unresolved"?<p className="mt-2 text-sm">The request did not resolve to a supported aircraft family. Sources remain limited to your selection and have not been aircraft-filtered. Check document applicability before relying on this topic.</p>:result.applicabilityAudit.unknown.length>0&&<p className="mt-2 text-sm">Excluded because applicability could not be resolved: {result.applicabilityAudit.unknown.map(id=>documents.find(d=>d.id===id)?.title??id).join(", ")}</p>}{result.applicabilityAudit.excluded.length>0&&<p className="mt-2 text-sm">Excluded as mismatched applicability: {result.applicabilityAudit.excluded.map(id=>documents.find(d=>d.id===id)?.title??id).join(", ")}</p>}</section>}
    {result.excludedEvidence.length>0&&<details className="rounded border p-3"><summary className="cursor-pointer font-medium">Evidence retrieved but not included ({result.excludedEvidence.length})</summary><ul className="mt-2 space-y-2 text-sm">{result.excludedEvidence.map(item=>{const e=evidenceById.get(item.id);return <li key={item.id}>{e&&<Link className="underline" href={`/documents/${e.documentId}`}>{e.documentTitle}, p. {e.page}</Link>} — {item.reason}</li>;})}</ul></details>}
    <section className="space-y-2"><h4 className="font-medium">Sources</h4>{cited.map((id,index)=>{const e=evidenceById.get(id);return e?<details id={`source-${id}`} key={id} className="rounded border p-2"><summary className="cursor-pointer text-sm"><span className="font-medium">[S{index+1}]</span> <Link className="underline" href={`/documents/${e.documentId}`}>{e.documentTitle}, p. {e.page}</Link> · Rev {e.revision}</summary><p className="mt-1 text-xs text-muted-foreground">Applicability/effectivity: {e.applicability} · Content hash: {e.sourceHash??"unknown"}</p><blockquote className="mt-2 border-l-2 pl-3 text-sm">{e.quote}</blockquote></details>:null;})}</section>
  </article>;
}
