import {RecipeSourceStatus} from "@/components/article-source-status";
import {knowledgeFeature} from "@/lib/knowledge/contracts";
import Link from "next/link";
import { requireAuthWorkspaceContext } from "@/lib/auth-workspace";
import { listKnowledgeBundles } from "@/lib/knowledge-bundles";
import { getPrisma } from "@/lib/prisma";
import type { BuilderResult } from "@/lib/topic-builder-core";
import { TopicBuilderForm, TopicBuilderPoller } from "@/components/topic-builder-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { TopicSourcePicker } from "@/components/topic-source-picker";
export const dynamic="force-dynamic";
export default async function TopicBuilderPage(){
 const context=await requireAuthWorkspaceContext();
 const [collections,recipes]=await Promise.all([listKnowledgeBundles(context),getPrisma().topicBuilderRecipe.findMany({where:{workspaceId:context.workspaceId},include:{runs:{orderBy:{createdAt:"desc"},take:8}},orderBy:{updatedAt:"desc"}})]);
 const documents=await getPrisma().document.findMany({where:{workspaceId:context.workspaceId,deletedAt:null,OR:[{knowledgeBundleId:null},{knowledgeBundle:{is:{workspaceId:context.workspaceId,status:"active"}}}]},orderBy:{title:"asc"},select:{id:true,title:true,pages:true,knowledgeBundle:{select:{name:true}},extractedPages:{select:{warningCodes:true}}}});
 const sources=documents.map(d=>({id:d.id,title:d.title,collection:d.knowledgeBundle?.name??"Unassigned",pages:d.pages,ready:d.pages>0&&d.extractedPages.length===d.pages&&!d.extractedPages.some(p=>p.warningCodes.some(c=>/unreadable|failed/i.test(c)))}));
 const active=recipes.some(r=>r.runs.some(x=>["queued","running"].includes(x.status)));
 return <div className="mx-auto max-w-6xl space-y-8">{active&&<TopicBuilderPoller/>}<header><p className="text-sm text-muted-foreground">Documents → topic → concise knowledge → reviewed revision</p><h1 className="mt-2 text-3xl font-semibold">Topic builder</h1><p className="mt-2 max-w-3xl text-muted-foreground">Choose a topic and documents already in your library, or select whole source collections. Build one connected collection, then refresh it when documents change. Existing approved revisions stay intact.</p></header>
 <section className="rounded-xl border p-5"><h2 className="mb-4 text-xl font-semibold">Create a topic recipe</h2><TopicBuilderForm><input type="hidden" name="action" value="create"/><div className="grid gap-4 md:grid-cols-2"><label className="space-y-2">Topic<Input name="topic" required minLength={3} maxLength={250} placeholder="737 NG landing gear extension and retraction"/></label><label className="space-y-2">Aircraft / applicability<Input name="applicability" required placeholder="737 NG; keep configuration differences separate"/></label><label>Audience<select name="audience" className="mt-2 block w-full rounded-md border bg-background p-2"><option value="enthusiast">Aviation enthusiast</option><option value="pilot">Pilot</option><option value="maintenance">Maintenance</option><option value="pilot-and-maintenance">Pilot and maintenance</option></select></label>{knowledgeFeature("authoring")&&<label>Research mode<select name="researchMode" defaultValue="agentic" className="block w-full rounded border bg-background p-2"><option value="agentic">Agentic graph research</option><option value="exhaustive">Full document scan</option></select></label>}<label>Maximum words per article<Input name="maxWords" type="number" min={80} max={500} defaultValue={180}/></label></div><label className="block">Additional guidance<textarea name="instructions" maxLength={2000} className="mt-2 block w-full rounded-md border bg-background p-2" placeholder="Focus on principles, use plain language, and preserve source conditions."/></label><TopicSourcePicker documents={sources} collections={collections.map(c=>({id:c.id,name:c.name}))}/><p className="text-xs text-muted-foreground">Uses your workspace AI provider. Each refresh checks the collection and reuses unchanged extraction results. Text evidence is compiled; figure-only content is not interpreted by this workflow.</p><Button type="submit" disabled={!documents.length}>Create and generate</Button></TopicBuilderForm></section>
 {recipes.length===0&&<p className="text-muted-foreground">Your topic recipes will appear here.</p>}{recipes.map(recipe=><section key={recipe.id} className="space-y-4 rounded-xl border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{recipe.topic}</h2><p className="text-sm text-muted-foreground">{recipe.applicability} · {recipe.audience} · {recipe.maxWords} words/article · {recipe.documentIds.length ? `${recipe.documentIds.length} selected documents` : `${recipe.collectionIds.length} entire collections`}</p></div><TopicBuilderForm><input type="hidden" name="action" value="refresh"/><input type="hidden" name="id" value={recipe.id}/><Button variant="outline" type="submit">Refresh from documents</Button></TopicBuilderForm><TopicBuilderForm><input type="hidden" name="action" value="rewrite"/><input type="hidden" name="id" value={recipe.id}/><Button variant="outline" type="submit">Rewrite articles</Button></TopicBuilderForm></div>
 <RecipeSourceStatus workspaceId={context.workspaceId} collectionIds={recipe.collectionIds} documentIds={recipe.documentIds} fingerprint={recipe.runs[0]?.fingerprint}/>
 <details className="rounded border p-3"><summary>Edit recipe and sources</summary><TopicBuilderForm><input type="hidden" name="action" value="edit"/><input type="hidden" name="id" value={recipe.id}/><input type="hidden" name="topic" value={recipe.topic}/><input type="hidden" name="audience" value={recipe.audience}/><input type="hidden" name="applicability" value={recipe.applicability}/><input type="hidden" name="researchMode" value={recipe.researchMode}/><label>Maximum words<Input name="maxWords" type="number" min={80} max={500} defaultValue={recipe.maxWords}/></label><label>Writing guidance<textarea name="instructions" defaultValue={recipe.instructions} maxLength={2000} className="block w-full rounded border bg-background p-2"/></label><TopicSourcePicker documents={sources} collections={collections.map(c=>({id:c.id,name:c.name}))} initialDocuments={recipe.documentIds} initialCollections={recipe.collectionIds}/><Button>Save and build revised draft</Button><p className="text-xs">Changed sources trigger research. Writing changes reuse valid source scans. Earlier approved revisions remain available.</p></TopicBuilderForm></details>
 {recipe.runs.map((run,index)=>{const result=run.result as unknown as BuilderResult|null; const changes=run.changes as {added:string[];updated:string[];removed:string[];conflicts:number}|null;return <details key={run.id} open={index===0} className="rounded-md border p-4"><summary className="cursor-pointer font-medium">{run.status} · {run.createdAt.toLocaleString()} {recipe.approvedRunId===run.id?"· current approved revision":""}</summary><p role="status" className="my-2 text-sm text-muted-foreground">{run.progress}</p>{run.error&&<p role="alert" className="text-sm text-destructive">{run.error.replaceAll("_"," ")}</p>}{changes&&<p className="text-sm">{changes.added.length} added · {changes.updated.length} updated · {changes.removed.length} removed · {changes.conflicts} conflicts</p>}
 {result&&<div className="my-4 space-y-3">{result.conflicts.length>0&&<div className="rounded-md border border-amber-500 p-3"><h3 className="font-semibold">Source conflicts</h3>{result.conflicts.map((c,i)=><p key={i} className="mt-2 text-sm">{c.description}</p>)}</div>}{result.articles.map(a=><article key={a.id} className="rounded-md bg-muted/40 p-4"><h3 className="font-semibold">{a.title}</h3><p className="my-2 text-sm leading-6">{a.answer}</p><ul className="list-disc space-y-1 pl-5 text-sm">{a.keyPoints.map((p,i)=><li key={i}>{p.text}</li>)}</ul><details className="mt-3 text-sm"><summary className="cursor-pointer">Details and sources</summary>{a.details.map((d,i)=><section key={i} className="mt-3"><h4 className="font-medium">{d.heading}</h4><p>{d.text}</p></section>)}{[...new Set([...a.evidenceIds,...a.keyPoints.flatMap(x=>x.evidenceIds),...a.details.flatMap(x=>x.evidenceIds)])].map(id=>{const e=result.evidence.find(x=>x.id===id);return e?<blockquote key={id} className="my-3 border-l-2 pl-3"><Link className="underline" href={`/documents/${e.documentId}`}>{e.documentTitle}, p. {e.page}</Link><p className="text-xs text-muted-foreground">Revision {e.revision} · {e.applicability} · {e.authority}</p><p className="mt-1 text-xs">{e.quote}</p></blockquote>:null;})}<p className="mt-3">Connections: {a.relationships.map(r=>`${r.relation.replaceAll("_"," ")} → ${r.target}`).join("; ")||"None"}</p></details></article>)}</div>}
 {run.status==="ready"&&<TopicBuilderForm><input type="hidden" name="action" value="approve"/><input type="hidden" name="id" value={run.id}/>{!!result?.conflicts.length&&<label className="flex gap-2 text-sm"><input type="checkbox" name="acceptConflicts" required/>Keep the listed conflicts visible in this educational revision.</label>}<Button type="submit">Approve this revision</Button></TopicBuilderForm>}
 {run.status==="approved"&&<a className="inline-block rounded-md border px-4 py-2 text-sm" href={`/api/topic-builder/${run.id}/export`}>Download native OKF bundle</a>}
 {["queued","running"].includes(run.status)&&<TopicBuilderForm><input type="hidden" name="action" value="cancel"/><input type="hidden" name="id" value={run.id}/><Button type="submit" variant="outline">Cancel generation</Button></TopicBuilderForm>}
 </details>;})}</section>)}<p className="text-xs text-muted-foreground">Approval versions this educational bundle. Download produces native OKF files for the existing publishing boundary; it does not activate an EFB production release.</p></div>;
}
